export const data = [
  {
    id: 1,
    userName: "John Doe",
    handle: "@johndoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 52,
    followers: 100,
  },
  {
    id: 2,
    userName: "Jan Doe",
    handle: "@jandoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 100,
    followers: 200,
  },
  {
    id: 3,
    userName: "Vishal",
    handle: "@vishal",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 200,
    followers: 300,
  },
  {
    id: 4,
    userName: "Rahul",
    handle: "@rahul",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 300,
    followers: 400,
  },
  {
    id: 5,
    userName: "Raj",
    handle: "@raj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 400,
    followers: 500,
  },
  {
    id: 6,
    userName: "Rohan sukla",
    handle: "@rohansukla",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 500,
    followers: 600,
  },
  {
    id: 7,
    userName: "Rahul mohak",
    handle: "@rahulmohak",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 600,
    followers: 700,
  },
  {
    id: 8,
    userName: "Raj kumar",
    handle: "@rajkumar",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 700,
    followers: 800,
  },
  {
    id: 9,
    userName: "Rohan raj",
    handle: "@rohanraj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 800,
    followers: 900,
  },
  {
    id: 10,
    userName: "Rohan singh",
    handle: "@rohansingh",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 900,
    followers: 1000,
  },
  {
    id: 11,
    userName: "John Doe",
    handle: "@johndoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 52,
    followers: 100,
  },
  {
    id: 12,
    userName: "Jan Doe",
    handle: "@jandoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 100,
    followers: 200,
  },
  {
    id: 13,
    userName: "Vishal",
    handle: "@vishal",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 200,
    followers: 300,
  },
  {
    id: 14,
    userName: "Rahul",
    handle: "@rahul",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 300,
    followers: 400,
  },
  {
    id: 15,
    userName: "Raj",
    handle: "@raj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 400,
    followers: 500,
  },
  {
    id: 16,
    userName: "Rohan sukla",
    handle: "@rohansukla",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 500,
    followers: 600,
  },
  {
    id: 17,
    userName: "Rahul mohak",
    handle: "@rahulmohak",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 600,
    followers: 700,
  },
  {
    id: 18,
    userName: "Raj kumar",
    handle: "@rajkumar",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 700,
    followers: 800,
  },
  {
    id: 19,
    userName: "Rohan raj",
    handle: "@rohanraj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 800,
    followers: 900,
  },
  {
    id: 20,
    userName: "Rohan singh",
    handle: "@rohansingh",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 900,
    followers: 1000,
  },
  {
    id: 21,
    userName: "John Doe",
    handle: "@johndoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 52,
    followers: 100,
  },
  {
    id: 22,
    userName: "Jan Doe",
    handle: "@jandoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 100,
    followers: 200,
  },
  {
    id: 23,
    userName: "Vishal",
    handle: "@vishal",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 200,
    followers: 300,
  },
  {
    id: 24,
    userName: "Rahul",
    handle: "@rahul",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 300,
    followers: 400,
  },
  {
    id: 25,
    userName: "Raj",
    handle: "@raj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 400,
    followers: 500,
  },
  {
    id: 26,
    userName: "Rohan sukla",
    handle: "@rohansukla",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 500,
    followers: 600,
  },
  {
    id: 27,
    userName: "Rahul mohak",
    handle: "@rahulmohak",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 600,
    followers: 700,
  },
  {
    id: 28,
    userName: "Raj kumar",
    handle: "@rajkumar",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 700,
    followers: 800,
  },
  {
    id: 29,
    userName: "Rohan raj",
    handle: "@rohanraj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 800,
    followers: 900,
  },
  {
    id: 30,
    userName: "Rohan singh",
    handle: "@rohansingh",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 900,
    followers: 1000,
  },
  {
    id: 31,
    userName: "John Doe",
    handle: "@johndoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 52,
    followers: 100,
  },
  {
    id: 32,
    userName: "Jan Doe",
    handle: "@jandoe",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 100,
    followers: 200,
  },
  {
    id: 33,
    userName: "Vishal",
    handle: "@vishal",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 200,
    followers: 300,
  },
  {
    id: 34,
    userName: "Rahul",
    handle: "@rahul",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 300,
    followers: 400,
  },
  {
    id: 35,
    userName: "Raj",
    handle: "@raj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 400,
    followers: 500,
  },
  {
    id: 36,
    userName: "Rohan sukla",
    handle: "@rohansukla",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Google",
    repo: 500,
    followers: 600,
  },
  {
    id: 37,
    userName: "Rahul mohak",
    handle: "@rahulmohak",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Facebook",
    repo: 600,
    followers: 700,
  },
  {
    id: 38,
    userName: "Raj kumar",
    handle: "@rajkumar",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Microsoft",
    repo: 700,
    followers: 800,
  },
  {
    id: 39,
    userName: "Rohan raj",
    handle: "@rohanraj",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Amazon",
    repo: 800,
    followers: 900,
  },
  {
    id: 40,
    userName: "Rohan singh",
    handle: "@rohansingh",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workAt: "Apple",
    repo: 900,
    followers: 1000,
  },
];
